
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 22 23:12:12 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 25;
  public static final int GREATER_OR_EQUAL = 39;
  public static final int RIGHT_BRACKET = 27;
  public static final int INCREMENT = 14;
  public static final int CONST = 3;
  public static final int charConst = 7;
  public static final int NOT_EQUAL = 43;
  public static final int LOWER = 42;
  public static final int GREATER = 41;
  public static final int CONTINUE = 36;
  public static final int boolConst = 8;
  public static final int INTERFACE = 31;
  public static final int LOWER_OR_EQUAL = 40;
  public static final int FOR = 34;
  public static final int DECREMENT = 15;
  public static final int AND = 44;
  public static final int OR = 45;
  public static final int COMMA = 10;
  public static final int LEFT_BRACE = 28;
  public static final int CLASS = 30;
  public static final int DIV = 22;
  public static final int IF = 37;
  public static final int DOT = 11;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int EQUAL = 18;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 21;
  public static final int ADD = 19;
  public static final int SEMI_COLON = 9;
  public static final int RIGHT_BRACE = 29;
  public static final int MOD = 23;
  public static final int BREAK = 35;
  public static final int IDENT = 5;
  public static final int VOID = 13;
  public static final int ELSE = 38;
  public static final int ENUM = 4;
  public static final int READ = 16;
  public static final int EXTENDS = 32;
  public static final int LEFT_PAREN = 24;
  public static final int numConst = 6;
  public static final int LEFT_BRACKET = 26;
  public static final int SUB = 20;
  public static final int PRINT = 17;
}

