
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
 
	// Keywords
	public static final int PROGRAM = 1;
	public static final int BREAK = 2;
	public static final int CLASS = 3;
	public static final int INTERFACE = 4;
	public static final int ENUM = 5;
	public static final int ELSE = 6;
	public static final int CONST = 7;
	public static final int IF = 8;
	public static final int NEW = 9;
	public static final int PRINT = 10;
	public static final int READ = 11;
	public static final int RETURN = 12;
	public static final int VOID = 13;
	public static final int FOR = 14;
	public static final int EXTENDS = 15;
	public static final int CONTINUE = 16;
	
	// Tokens
	public static final int IDENT = 17;
	public static final int numConst = 18;
	public static final int charConst = 19;
	public static final int boolConst = 20;
	
	// Operators
	public static final int ADD = 21;
	public static final int SUB = 22;
	public static final int MUL = 23;
	public static final int DIV = 24;
	public static final int MOD = 25;
	public static final int EQUAL = 26;
	public static final int NOT_EQUAL = 27;
	public static final int GREATER = 28;
	public static final int GREATER_OR_EQUAL = 29;
	public static final int LOWER = 30;
	public static final int LOWER_OR_EQUAL = 31;
	public static final int AND = 32;
	public static final int OR = 33;
	public static final int ASSIGN = 34;
	public static final int INCREMENT = 35;
	public static final int DECREMENT = 36;
	public static final int SEMI_COLON = 37;
	public static final int COMMA = 38;
	public static final int DOT = 39;
	public static final int LEFT_PAREN = 40;
	public static final int RIGHT_PAREN = 41;
	public static final int LEFT_BRACKET = 42;
	public static final int RIGHT_BRACKET = 43;
	public static final int LEFT_BRACE = 44;
	public static final int RIGHT_BRACE = 45;
	
	// Comments
	public static final int COMMENT = 46;
	
	// EOF
	public static final int EOF = 47;
}